In [52]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
import warnings 
warnings.filterwarnings('ignore')

In [53]:
data =pd.read_csv("customer_shopping_behavior.csv")

In [54]:
data.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [55]:
data.tail()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
5045,913,24,Male,Hoodie,Clothing,56.0,Arkansas,M,Green,Winter,3.4,Yes,Next Day Air,Yes,32.0,Bank Transfer,Monthly
5046,3466,19,Female,Backpack,Accessories,53.0,Iowa,M,Gold,Spring,3.4,No,Standard,No,31.0,Debit Card,Weekly
5047,3572,70,Female,Skirt,Clothing,27.0,North Dakota,M,White,Summer,3.2,No,Standard,No,15.0,Bank Transfer,Every 3 Months
5048,3195,43,Female,Sneakers,Footwear,52.0,Maryland,L,Gold,Summer,4.6,No,Standard,No,10.0,Credit Card,Bi-Weekly
5049,1832,62,Male,Blouse,Clothing,71.0,Maine,M,Cyan,Summer,3.3,No,Free Shipping,No,5.0,Bank Transfer,Every 3 Months

In [56]:
data.shape

(5050, 17)

In [57]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             5050 non-null   int64
 1   Age                     5050 non-null   int64
 2   Gender                  5050 non-null   object
 3   Item Purchased          5050 non-null   object
 4   Category                5050 non-null   object
 5   Purchase Amount (USD)   4494 non-null   float64
 6   Location                5050 non-null   object
 7   Size                    4680 non-null   object
 8   Color                   5050 non-null   object
 9   Season                  5050 non-null   object
 10  Review Rating           4449 non-null   float64
 11  Subscription Status     5050 non-null   object
 12  Shipping Type           5050 non-null   object
 13  Discount Applied        5050 non-null   object
 14  Previous Purchases      4502 non-null   float64
 15  Payment Method          5050 non-null   object
 16  Frequency of Purchases  5050 non-null   object
dtypes: float64(3), int64(2), object(12)
memory usage: 670.8+ KB

In [59]:
data.dtypes

Customer ID                 int64
Age                         int64
Gender                     object
Item Purchased             object
Category                   object
Purchase Amount (USD)     float64
Location                   object
Size                       object
Color                      object
Season                     object
Review Rating             float64
Subscription Status        object
Shipping Type              object
Discount Applied           object
Previous Purchases        float64
Payment Method             object
Frequency of Purchases     object
dtype: object

#### Data Cleaning

In [60]:
data.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [61]:
data['Purchase Amount (USD)'].fillna(data['Purchase Amount (USD)'].median(),inplace=True)

In [62]:
data['Size'].fillna(data['Size'].mode()[0], inplace=True)

In [109]:
data['Review Rating'].fillna(data['Review Rating'].mean(),inplace=True)

In [108]:
data['Previous Purchases'].fillna(0).round(2)

0       36.00
1       20.00
2       18.00
3       25.00
4       17.00
5       15.00
6        2.00
7       18.00
8       28.00
9        7.00
10      41.00
11       4.00
12      25.22
13       4.00
14      30.00
15      18.00
16      33.00
17      39.00
18      18.00
19      13.00
20      25.00
21      28.00
22       6.00
23      25.00
24      25.22
25       6.00
26      36.00
27      20.00
28      50.00
29      50.00
30      24.00
31       8.00
32      24.00
33       5.00
34      45.00
35      31.00
36      16.00
37      15.00
38      47.00
39       4.00
40      47.00
41      37.00
42      31.00
43      28.00
44       1.00
45      34.00
46      12.00
47      20.00
48      39.00
49      28.00
50       0.00
51      31.00
52      17.00
53      47.00
54      25.22
55       9.00
56      16.00
57      47.00
58      25.22
59      27.00
60      40.00
61      37.00
62      25.00
63      26.00
64       4.00
65      27.00
66      32.00
67      25.22
68      33.00
69      41.00
70       5.00
71      48.00
72      25.22
73      38.00
74      25.22
75      18.00
76      32.00
77      22.00
78      29.00
79      48.00
80      29.00
81      11.00
82       7.00
83      25.22
84       8.00
85      26.00
86      18.00
87      18.00
88      44.00
89      40.00
90      35.00
91      19.00
92       5.00
93      29.00
94       2.00
95      20.00
96      31.00
97      25.22
98      10.00
99      14.00
100      4.00
101     25.22
102     31.00
103     15.00
104      2.00
105      1.00
106     44.00
107     25.22
108      4.00
109      3.00
110      7.00
111     49.00
112     26.00
113      1.00
114     49.00
115     25.22
116     46.00
117     19.00
118     25.22
119     29.00
120     36.00
121     36.00
122     43.00
123     32.00
124     13.00
125     44.00
126     12.00
127     38.00
128     30.00
129     25.22
130     39.00
131      5.00
132     45.00
133     42.00
134     40.00
135     33.00
136     37.00
137     44.00
138      9.00
139     16.00
140     25.22
141     24.00
142     25.22
143     25.22
144     24.00
145      4.00
146      6.00
147      6.00
148     40.00
149     40.00
150      8.00
151     33.00
152      8.00
153     19.00
154     38.00
155     25.22
156     44.00
157      6.00
158      5.00
159     38.00
160     15.00
161      2.00
162     25.22
163      3.00
164     37.00
165      7.00
166     37.00
167     25.00
168     25.22
169     19.00
170     25.22
171     20.00
172     30.00
173     35.00
174      4.00
175     30.00
176     19.00
177     43.00
178     24.00
179     14.00
180     11.00
181     17.00
182      2.00
183      9.00
184     50.00
185      8.00
186     43.00
187     30.00
188      5.00
189     32.00
190     25.22
191     21.00
192     17.00
193      9.00
194     39.00
195     36.00
196     25.22
197     48.00
198     43.00
199     28.00
200     25.22
201     32.00
202     34.00
203      4.00
204     25.22
205      1.00
206     41.00
207     48.00
208      6.00
209     15.00
210     28.00
211     17.00
212     11.00
213     46.00
214     39.00
215      5.00
216     33.00
217     25.22
218     30.00
219     48.00
220     50.00
221     47.00
222     25.22
223     24.00
224     40.00
225     28.00
226     23.00
227     20.00
228     25.22
229      8.00
230      3.00
231     31.00
232      1.00
233     47.00
234     24.00
235      1.00
236     30.00
237     45.00
238     30.00
239     24.00
240     25.22
241     26.00
242     11.00
243     41.00
244     50.00
245     20.00
246      2.00
247     35.00
248     32.00
249     25.22
250     42.00
251     20.00
252     25.22
253     25.22
254     25.22
255     46.00
256     13.00
257      8.00
258     30.00
259     47.00
260     40.00
261      2.00
262     15.00
263     47.00
264     15.00
265     47.00
266     28.00
267     48.00
268     14.00
269     46.00
270      2.00
271     48.00
272     27.00
273     47.00
274     40.00
275     19.00
276     25.22
277     10.00
278     27.00
279      4.00
280     25.00
281     42.00
282     21.00
283     15.00
284     18.00
285     36.00
286     12.00
287     47.00
288     44.00
289     13.00
290     37.00
291     44.00
292     41.00
293     15.00
294     44.00
295     39.00
296     17.00
297     47.00
298      4.00
299      2.00
300      8.00
301     13.00
302     40.00
303     35.00
304     44.00
305     46.00
306     33.00
307     12.00
308     21.00
309      4.00
310     15.00
311     29.00
312     28.00
313      2.00
314     22.00
315     10.00
316     25.22
317     25.22
318     26.00
319     49.00
320     11.00
321      1.00
322     33.00
323     34.00
324     41.00
325     17.00
326     35.00
327     33.00
328     25.22
329     36.00
330     33.00
331     28.00
332      9.00
333      8.00
334     17.00
335     39.00
336     43.00
337      7.00
338     25.22
339     36.00
340      7.00
341     20.00
342     25.22
343     25.22
344     18.00
345     31.00
346     30.00
347     28.00
348     42.00
349     47.00
350     11.00
351     25.22
352     40.00
353     41.00
354     25.22
355     18.00
356     36.00
357     25.22
358     33.00
359     28.00
360     25.22
361      7.00
362     25.22
363     31.00
364     41.00
365     39.00
366     30.00
367     18.00
368     27.00
369     34.00
370     25.22
371      8.00
372     35.00
373      8.00
374     25.22
375     17.00
376      2.00
377     34.00
378     42.00
379     13.00
380     10.00
381     45.00
382     10.00
383     50.00
384     25.22
385     28.00
386      1.00
387     25.22
388     21.00
389     13.00
390     47.00
391     29.00
392     42.00
393     32.00
394     15.00
395      9.00
396     13.00
397     25.22
398     16.00
399     10.00
400     16.00
401     27.00
402     32.00
403     31.00
404     28.00
405     41.00
406      6.00
407     31.00
408     40.00
409     26.00
410      6.00
411     49.00
412     27.00
413     20.00
414     18.00
415      5.00
416     37.00
417     26.00
418     33.00
419     26.00
420     25.22
421      8.00
422     29.00
423     50.00
424      1.00
425     42.00
426      2.00
427     29.00
428     43.00
429      9.00
430     20.00
431     21.00
432     11.00
433     17.00
434     17.00
435      6.00
436     25.22
437     50.00
438     29.00
439      9.00
440     13.00
441     27.00
442     11.00
443     20.00
444     39.00
445     16.00
446     25.22
447     31.00
448     30.00
449     36.00
450     36.00
451     15.00
452     26.00
453     21.00
454      3.00
455     31.00
456     32.00
457     40.00
458     47.00
459      1.00
460     10.00
461     25.22
462     31.00
463     12.00
464     23.00
465     32.00
466      1.00
467      1.00
468     23.00
469     28.00
470     25.22
471     43.00
472     28.00
473     14.00
474      1.00
475     25.22
476     30.00
477     13.00
478      9.00
479     19.00
480     41.00
481     44.00
482     34.00
483     30.00
484     43.00
485     30.00
486     17.00
487     45.00
488     27.00
489     14.00
490     25.22
491     12.00
492     19.00
493     50.00
494     19.00
495     24.00
496     42.00
497     50.00
498      3.00
499      2.00
500     33.00
501      6.00
502     20.00
503     31.00
504     47.00
505     11.00
506     48.00
507     49.00
508      6.00
509     22.00
510     19.00
511     34.00
512     43.00
513      8.00
514      9.00
515     21.00
516     26.00
517     11.00
518     41.00
519     14.00
520      6.00
521      3.00
522     26.00
523     32.00
524     12.00
525     14.00
526     45.00
527     26.00
528     21.00
529     17.00
530     48.00
531     46.00
532     35.00
533      3.00
534     26.00
535     39.00
536      4.00
537     20.00
538     38.00
539     14.00
540      4.00
541     36.00
542     24.00
543     46.00
544      9.00
545     20.00
546     49.00
547     45.00
548     42.00
549     25.22
550     28.00
551     42.00
552      8.00
553     11.00
554     25.22
555     43.00
556     18.00
557     23.00
558     41.00
559     50.00
560     34.00
561     50.00
562      6.00
563      2.00
564      6.00
565     25.22
566     10.00
567     23.00
568     25.22
569     11.00
570      9.00
571     41.00
572     14.00
573      8.00
574     47.00
575     45.00
576     27.00
577     36.00
578     25.22
579     25.22
580     25.22
581     24.00
582      3.00
583     29.00
584      9.00
585     35.00
586     15.00
587     14.00
588      6.00
589     30.00
590     27.00
591     36.00
592      2.00
593     38.00
594     26.00
595     41.00
596      9.00
597     34.00
598     50.00
599     20.00
600     25.22
601     11.00
602     48.00
603      3.00
604     16.00
605     21.00
606      9.00
607     32.00
608     25.22
609      7.00
610     14.00
611      2.00
612     30.00
613     14.00
614     49.00
615     14.00
616     44.00
617     50.00
618      6.00
619     20.00
620     25.00
621     43.00
622      9.00
623     19.00
624     48.00
625     20.00
626     15.00
627     12.00
628     20.00
629     33.00
630     25.22
631      0.00
632     25.22
633     25.22
634     25.22
635     42.00
636     40.00
637     35.00
638      2.00
639     47.00
640      6.00
641     24.00
642      1.00
643     13.00
644     31.00
645      7.00
646     20.00
647     25.22
648     28.00
649     15.00
650     50.00
651      1.00
652     31.00
653     16.00
654     33.00
655     22.00
656     25.22
657     28.00
658     50.00
659     33.00
660     43.00
661     16.00
662     10.00
663     14.00
664     11.00
665     21.00
666     21.00
667     12.00
668     45.00
669     15.00
670     42.00
671     45.00
672     46.00
673     46.00
674     25.22
675     18.00
676     40.00
677      2.00
678     25.22
679     28.00
680     46.00
681     44.00
682     43.00
683     43.00
684     34.00
685     38.00
686     37.00
687     25.22
688      1.00
689     31.00
690     25.00
691      4.00
692     25.22
693     34.00
694     26.00
695     34.00
696     25.00
697     38.00
698     10.00
699     29.00
700     15.00
701     36.00
702     23.00
703     40.00
704     13.00
705     42.00
706     30.00
707     44.00
708     13.00
709     29.00
710     31.00
711     37.00
712     33.00
713     25.22
714      6.00
715     28.00
716     29.00
717     12.00
718     40.00
719     32.00
720      2.00
721     11.00
722     43.00
723     35.00
724     18.00
725     10.00
726     12.00
727      8.00
728     31.00
729     45.00
730     12.00
731     21.00
732      5.00
733     25.22
734      8.00
735     33.00
736      4.00
737      4.00
738     29.00
739     43.00
740     36.00
741     25.22
742      1.00
743     26.00
744     37.00
745      1.00
746     33.00
747     46.00
748     39.00
749     43.00
750      5.00
751     26.00
752     43.00
753     46.00
754     11.00
755      3.00
756     25.22
757     25.00
758     14.00
759     38.00
760      1.00
761     45.00
762      9.00
763      3.00
764     48.00
765     31.00
766      3.00
767     44.00
768     28.00
769     43.00
770     23.00
771     18.00
772     35.00
773     19.00
774     25.22
775      5.00
776     25.22
777     40.00
778     41.00
779     46.00
780     15.00
781     31.00
782     28.00
783     10.00
784     10.00
785     33.00
786     18.00
787     40.00
788     46.00
789     28.00
790     45.00
791      3.00
792     10.00
793     41.00
794      7.00
795     13.00
796     30.00
797     28.00
798      4.00
799     18.00
800     14.00
801     24.00
802      5.00
803     25.00
804     25.00
805      4.00
806     25.22
807     44.00
808     48.00
809     11.00
810     29.00
811     13.00
812     32.00
813     42.00
814     41.00
815      2.00
816     37.00
817     40.00
818     21.00
819     18.00
820     24.00
821     25.22
822     21.00
823     25.22
824     47.00
825      1.00
826     37.00
827     35.00
828     21.00
829     27.00
830     42.00
831     45.00
832     26.00
833     22.00
834     16.00
835      3.00
836     28.00
837     36.00
838     24.00
839     34.00
840     25.22
841     19.00
842     25.22
843      1.00
844     43.00
845     19.00
846     46.00
847     41.00
848     48.00
849     14.00
850      6.00
851     49.00
852     47.00
853     25.00
854     21.00
855     31.00
856     14.00
857     41.00
858     48.00
859     45.00
860     12.00
861     17.00
862      4.00
863      8.00
864     13.00
865     50.00
866     21.00
867     36.00
868     48.00
869     35.00
870     31.00
871      5.00
872      6.00
873      0.00
874      3.00
875     48.00
876     50.00
877     12.00
878      9.00
879     25.22
880     40.00
881     44.00
882      4.00
883     27.00
884     22.00
885     25.22
887     15.00
888     35.00
889     48.00
890     28.00
891     20.00
892     43.00
893     34.00
894     16.00
895     25.22
896     27.00
897     23.00
898     22.00
899     29.00
900     25.22
901     42.00
902      4.00
903     27.00
904     20.00
905     17.00
906     11.00
907     25.22
908     11.00
909      6.00
910     48.00
911     25.22
912     25.22
913     47.00
914     46.00
915     11.00
916     18.00
917      6.00
918     25.22
919     38.00
920     32.00
921     42.00
922     47.00
923     11.00
924     27.00
925     29.00
926     10.00
927     33.00
928     32.00
929      3.00
930     23.00
931     38.00
932     25.22
933     25.22
934     25.22
935     41.00
936     19.00
937     25.00
938     48.00
939     36.00
940     11.00
941     25.22
942     47.00
943     21.00
944     48.00
945      3.00
946     20.00
947     27.00
948     10.00
949     48.00
950     42.00
951     32.00
952     48.00
953     25.22
954     21.00
955     13.00
956     23.00
957      1.00
958     36.00
959      6.00
960     50.00
961     46.00
962      9.00
963      3.00
964     44.00
965     28.00
966     19.00
967     48.00
968     13.00
969      6.00
970     16.00
971     16.00
972      6.00
973     45.00
974     37.00
975     12.00
976     38.00
977     14.00
978     31.00
979     25.22
980     34.00
981     20.00
982      4.00
983     40.00
984     15.00
985     11.00
986      0.00
987     32.00
988     11.00
989     35.00
990     25.22
991     10.00
992      4.00
993     23.00
994     12.00
995      2.00
996     38.00
997     34.00
998     37.00
999     48.00
1000    25.22
1001    47.00
1002    42.00
1003    44.00
1004    34.00
1005    22.00
1006    18.00
1007    48.00
1008     5.00
1009    39.00
1010    26.00
1011     6.00
1012     2.00
1013     2.00
1014    25.22
1015    46.00
1016    19.00
1017    14.00
1018    47.00
1019    42.00
1020    50.00
1021    44.00
1022    39.00
1023    25.22
1024    37.00
1025     8.00
1026     2.00
1027     4.00
1028     3.00
1029    11.00
1030    36.00
1031    31.00
1032    46.00
1033    12.00
1034    50.00
1035    41.00
1036    29.00
1037     4.00
1038     9.00
1039     9.00
1040    12.00
1041     4.00
1042    22.00
1043    42.00
1044    40.00
1045    17.00
1046     8.00
1047    12.00
1048    21.00
1049    25.00
1050    10.00
1051    11.00
1052    48.00
1053    50.00
1054    11.00
1055    21.00
1056    49.00
1057    32.00
1058    25.22
1059    25.22
1060    10.00
1061    40.00
1062    23.00
1063     3.00
1064    47.00
1065    34.00
1066    47.00
1067    15.00
1068     2.00
1069     0.00
1070    48.00
1071    50.00
1072    50.00
1073    48.00
1074    32.00
1075    23.00
1076     0.00
1077    41.00
1078    48.00
1079    48.00
1080    14.00
1081    45.00
1082     5.00
1083    26.00
1084    34.00
1085    49.00
1086    25.22
1087     8.00
1088     3.00
1089    30.00
1090    25.00
1091    27.00
1092    27.00
1093     3.00
1094    25.22
1095    30.00
1096    25.22
1097    25.22
1098     7.00
1099    25.22
1100    37.00
1101    11.00
1102    14.00
1103    33.00
1104    23.00
1105    50.00
1106    39.00
1107    35.00
1108    21.00
1109    15.00
1110    22.00
1111    43.00
1112    17.00
1113    34.00
1114    47.00
1115    40.00
1116    15.00
1117    19.00
1118    49.00
1119    48.00
1120    25.22
1121    50.00
1122    37.00
1123    42.00
1124    19.00
1125    25.22
1126    48.00
1127    40.00
1128    18.00
1129     4.00
1130    33.00
1131    25.22
1132    19.00
1133    32.00
1134    45.00
1135    39.00
1136    23.00
1137    36.00
1138    26.00
1139    30.00
1140    40.00
1141    44.00
1142    39.00
1143    24.00
1144    32.00
1145    10.00
1146    47.00
1147    33.00
1148     3.00
1149    18.00
1150    48.00
1151    25.22
1152    30.00
1153    20.00
1154    38.00
1155     4.00
1156    36.00
1157    30.00
1158    38.00
1159     4.00
1160    37.00
1161    23.00
1162    25.22
1163    25.22
1164     3.00
1165    25.22
1166    33.00
1167    33.00
1168    31.00
1169    25.22
1170    42.00
1171     3.00
1172    23.00
1173     6.00
1174    42.00
1175    37.00
1176    45.00
1177    34.00
1178    30.00
1179    17.00
1180    43.00
1181    41.00
1182    44.00
1183    35.00
1184    25.22
1185    15.00
1186    32.00
1187    34.00
1188    40.00
1189    35.00
1190    15.00
1191    31.00
1192     7.00
1193    38.00
1194     9.00
1195    18.00
1196    17.00
1197    30.00
1198    26.00
1199     6.00
1200    21.00
1201    46.00
1202    21.00
1203    20.00
1204    21.00
1205    47.00
1206     2.00
1207    15.00
1208    30.00
1209     3.00
1210    25.22
1211    19.00
1212    20.00
1213    29.00
1214    31.00
1215     7.00
1216    46.00
1217     6.00
1218    41.00
1219    25.22
1220    45.00
1221    24.00
1222    10.00
1223    48.00
1224    17.00
1225    50.00
1226    32.00
1227    39.00
1228     5.00
1229    25.22
1230    43.00
1231    33.00
1232    25.00
1233    11.00
1234    24.00
1235    31.00
1236    45.00
1237     5.00
1238    48.00
1239    11.00
1240    25.22
1241    45.00
1242    25.22
1243    29.00
1244    33.00
1245    22.00
1246    29.00
1247    26.00
1248    23.00
1249    23.00
1250    36.00
1251    28.00
1252    39.00
1253    22.00
1254    25.22
1255    36.00
1256    44.00
1257     7.00
1258     5.00
1259    17.00
1260    25.22
1261    14.00
1262    32.00
1263     9.00
1264    47.00
1265    29.00
1266    31.00
1267    37.00
1268    39.00
1269    25.22
1270    25.22
1271    31.00
1272    30.00
1273    20.00
1274     7.00
1275    25.22
1276    25.22
1277    25.22
1278     9.00
1279    25.22
1280    23.00
1281    26.00
1282    44.00
1283     7.00
1284    16.00
1285    44.00
1286    46.00
1287    24.00
1288    16.00
1289     2.00
1290    21.00
1291    18.00
1292    24.00
1293    25.00
1294    10.00
1295     3.00
1296     8.00
1297    36.00
1298    48.00
1299    14.00
1300     5.00
1301     5.00
1302     3.00
1303     5.00
1304    33.00
1305    20.00
1306    35.00
1307    39.00
1308    46.00
1309    44.00
1310    25.22
1311    10.00
1312    21.00
1313    49.00
1314    31.00
1315    50.00
1316    45.00
1317    25.00
1318    22.00
1319    17.00
1320    35.00
1321    42.00
1322    16.00
1323     9.00
1324    28.00
1325    29.00
1326    25.22
1327    11.00
1328     8.00
1329    25.22
1330    18.00
1331    25.22
1332    34.00
1333    34.00
1334    11.00
1335    50.00
1336    39.00
1337     8.00
1338    14.00
1339    14.00
1340    26.00
1341    25.00
1342    26.00
1343    18.00
1344    29.00
1345     7.00
1346    25.22
1347    41.00
1348    11.00
1349    25.22
1350     1.00
1351    28.00
1352    22.00
1353     6.00
1354    25.00
1355    12.00
1356    13.00
1357    28.00
1358    45.00
1359    25.22
1360    18.00
1361     4.00
1362    30.00
1363    29.00
1364    22.00
1365     8.00
1366    48.00
1367    38.00
1368     4.00
1369    36.00
1370     9.00
1371     5.00
1372    16.00
1373    30.00
1374    25.22
1375    42.00
1376    13.00
1377    32.00
1378    25.22
1379    45.00
1380    17.00
1381    25.22
1382    20.00
1383     5.00
1384    28.00
1385    25.22
1386    14.00
1387    13.00
1388     3.00
1389     2.00
1390    32.00
1391    23.00
1392    43.00
1393    44.00
1394    40.00
1395    25.22
1396    34.00
1397     1.00
1398    37.00
1399    16.00
1400    22.00
1401    43.00
1403    29.00
1404    13.00
1405    40.00
1406    21.00
1407    22.00
1408    16.00
1409    27.00
1410    21.00
1411    11.00
1412     6.00
1413    50.00
1414    47.00
1415    13.00
1416    25.22
1417    41.00
1418    25.22
1419    46.00
1420     5.00
1421    44.00
1422    42.00
1423    28.00
1424    14.00
1425    41.00
1426    38.00
1427    49.00
1428    46.00
1429    39.00

In [107]:
data.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [66]:
data.duplicated().sum()

np.int64(50)

In [67]:
data.drop_duplicates(inplace=True)

In [68]:
data.duplicated().sum()

np.int64(0)

In [70]:
data.shape

(5000, 17)

In [71]:
data['Item Purchased']

0          T-shirt
1       Sunglasses
2            Shirt
3           Gloves
4          Jewelry
           ...
5045        Hoodie
5046      Backpack
5047         Skirt
5048      Sneakers
5049        Blouse
Name: Item Purchased, Length: 5000, dtype: object

In [72]:
data['Item Purchased'].unique()

array(['T-shirt', 'Sunglasses', 'Shirt', 'Gloves', 'Jewelry', 'Shorts',
       'Hat', 'Handbag', 'Shoes', 'Coat', 'Laptop', 'Hoodie', 'Phone',
       'Jacket', 'Pants', 'Backpack', 'Socks', 'Jeans', 'Bag', 'Belt',
       'Watch', 'Headphones', 'Blouse', 'Sandals', 'Skirt', 'Sweater',
       'Scarf', 'Sneakers', 'Boots', 'Dress'], dtype=object)

In [75]:
data['Category'].unique()

array(['Clothing', 'Accessories', 'Outerwear', 'Electronics', 'Footwear'],
      dtype=object)

In [76]:
data.groupby('Category')['Item Purchased'].unique()

Category
Accessories    [Sunglasses, Gloves, Jewelry, Hat, Handbag, Ph...
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone,...
Electronics    [Laptop, Phone, Watch, Bag, Shoes, Shirt, Head...
Footwear                       [Shoes, Sandals, Sneakers, Boots]
Outerwear                                         [Coat, Jacket]
Name: Item Purchased, dtype: object

In [82]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows', None)

In [83]:
data.groupby('Category')['Item Purchased'].unique()

Category
Accessories               [Sunglasses, Gloves, Jewelry, Hat, Handbag, Phone, Backpack, Belt, Bag, Headphones, Scarf, Watch, Shirt, Shoes, Laptop]
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone, Pants, Socks, Jeans, Bag, Blouse, Skirt, Sweater, Watch, Laptop, Dress, Headphones]
Electronics                                                                                 [Laptop, Phone, Watch, Bag, Shoes, Shirt, Headphones]
Footwear                                                                                                        [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                                                                          [Coat, Jacket]
Name: Item Purchased, dtype: object

In [86]:
category_mapping={
   # Clothing
    'T-shirt': 'Clothing',
    'Shirt': 'Clothing',
    'Shorts': 'Clothing',
    'Jeans': 'Clothing',
    'Pants': 'Clothing',
    'Hoodie': 'Clothing',
    'Sweater': 'Clothing',
    'Blouse': 'Clothing',
    'Dress': 'Clothing',
    'Skirt': 'Clothing',
    'Socks': 'Clothing',

    # Footwear
    'Shoes': 'Footwear',
    'Sneakers': 'Footwear',
    'Sandals': 'Footwear',
    'Boots': 'Footwear',

    # Accessories
    'Hat': 'Accessories',
    'Belt': 'Accessories',
    'Scarf': 'Accessories',
    'Jewelry': 'Accessories',
    'Gloves': 'Accessories',
    'Handbag': 'Accessories',
    'Backpack': 'Accessories',
    'Bag': 'Accessories',
    'Sunglasses': 'Accessories',
    'Watch': 'Accessories',

    # Electronics
    'Phone': 'Electronics',
    'Laptop': 'Electronics',
    'Headphones': 'Electronics',

    # Outerwear
    'Jacket': 'Outerwear',
    'Coat': 'Outerwear'
}

In [87]:
category_mapping

{'T-shirt': 'Clothing',
 'Shirt': 'Clothing',
 'Shorts': 'Clothing',
 'Jeans': 'Clothing',
 'Pants': 'Clothing',
 'Hoodie': 'Clothing',
 'Sweater': 'Clothing',
 'Blouse': 'Clothing',
 'Dress': 'Clothing',
 'Skirt': 'Clothing',
 'Socks': 'Clothing',
 'Shoes': 'Footwear',
 'Sneakers': 'Footwear',
 'Sandals': 'Footwear',
 'Boots': 'Footwear',
 'Hat': 'Accessories',
 'Belt': 'Accessories',
 'Scarf': 'Accessories',
 'Jewelry': 'Accessories',
 'Gloves': 'Accessories',
 'Handbag': 'Accessories',
 'Backpack': 'Accessories',
 'Bag': 'Accessories',
 'Sunglasses': 'Accessories',
 'Watch': 'Accessories',
 'Phone': 'Electronics',
 'Laptop': 'Electronics',
 'Headphones': 'Electronics',
 'Jacket': 'Outerwear',
 'Coat': 'Outerwear'}

In [88]:
data['Category']=data['Item Purchased'].map(category_mapping)

In [89]:
data.groupby('Category')['Item Purchased'].unique()

Category
Accessories          [Sunglasses, Gloves, Jewelry, Hat, Handbag, Backpack, Bag, Belt, Watch, Scarf]
Clothing       [T-shirt, Shirt, Shorts, Hoodie, Pants, Socks, Jeans, Blouse, Skirt, Sweater, Dress]
Electronics                                                             [Laptop, Phone, Headphones]
Footwear                                                          [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                            [Coat, Jacket]
Name: Item Purchased, dtype: object

In [91]:
data.groupby('Category')['Size'].unique()

Category
Accessories    [M, L, S, XL]
Clothing       [XL, M, S, L]
Electronics    [M, L, S, XL]
Footwear       [M, L, S, XL]
Outerwear      [XL, L, S, M]
Name: Size, dtype: object

In [92]:
data.groupby('Item Purchased')['Size'].unique()

Item Purchased
Backpack      [M, S, L, XL]
Bag           [M, L, XL, S]
Belt          [M, S, XL, L]
Blouse        [M, L, S, XL]
Boots         [L, M, XL, S]
Coat          [XL, M, S, L]
Dress         [XL, M, L, S]
Gloves        [L, M, S, XL]
Handbag       [S, XL, M, L]
Hat           [M, L, S, XL]
Headphones    [S, M, L, XL]
Hoodie        [M, L, S, XL]
Jacket        [L, S, M, XL]
Jeans         [L, M, XL, S]
Jewelry       [L, XL, M, S]
Laptop        [M, S, XL, L]
Pants         [L, M, XL, S]
Phone         [M, L, S, XL]
Sandals       [M, S, L, XL]
Scarf         [M, L, S, XL]
Shirt         [M, XL, L, S]
Shoes         [M, L, XL, S]
Shorts        [S, M, L, XL]
Skirt         [S, L, M, XL]
Sneakers      [S, M, L, XL]
Socks         [M, XL, L, S]
Sunglasses    [M, L, S, XL]
Sweater       [M, S, L, XL]
T-shirt       [XL, M, S, L]
Watch         [M, L, XL, S]
Name: Size, dtype: object

In [93]:
data.groupby('Category')['Item Purchased'].unique()

Category
Accessories          [Sunglasses, Gloves, Jewelry, Hat, Handbag, Backpack, Bag, Belt, Watch, Scarf]
Clothing       [T-shirt, Shirt, Shorts, Hoodie, Pants, Socks, Jeans, Blouse, Skirt, Sweater, Dress]
Electronics                                                             [Laptop, Phone, Headphones]
Footwear                                                          [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                            [Coat, Jacket]
Name: Item Purchased, dtype: object

In [94]:
data.groupby('Category')['Size'].unique()

Category
Accessories    [M, L, S, XL]
Clothing       [XL, M, S, L]
Electronics    [M, L, S, XL]
Footwear       [M, L, S, XL]
Outerwear      [XL, L, S, M]
Name: Size, dtype: object

In [96]:
# treating null value and replacing all value in electronics categories.
data.loc[data['Category']=='Electronics','Size']="Not Applicable"

In [97]:
data.groupby('Category')['Size'].unique()

Category
Accessories       [M, L, S, XL]
Clothing          [XL, M, S, L]
Electronics    [Not Applicable]
Footwear          [M, L, S, XL]
Outerwear         [XL, L, S, M]
Name: Size, dtype: object

In [100]:
# treating null value and replacing all value in Accessories categories.
data.loc[data['Category']=='Accessories','Size']="Free Size"

In [101]:
data.groupby('Category')['Size'].unique()

Category
Accessories         [Free Size]
Clothing          [XL, M, S, L]
Electronics    [Not Applicable]
Footwear          [M, L, S, XL]
Outerwear         [XL, L, S, M]
Name: Size, dtype: object

In [104]:
# treating null value and replacing all value in footwear categories.
data.loc[data['Category']=='Footwear','Size']="Not Available"

In [105]:
data.groupby('Category')['Size'].unique()

Category
Accessories         [Free Size]
Clothing          [XL, M, S, L]
Electronics    [Not Applicable]
Footwear        [Not Available]
Outerwear         [XL, L, S, M]
Name: Size, dtype: object

#### Renaming the headers

In [110]:
data.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Previous Purchases', 'Payment Method',
       'Frequency of Purchases'],
      dtype='object')

In [113]:
data.columns=data.columns.str.replace(" ","_")
data.columns=data.columns.str.lower()

In [114]:
data.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [118]:
#replacing purchase_amount_(usd) into purchase_amount
data=data.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [119]:
data.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [129]:
data.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free Size,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free Size,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free Size,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

### connecting to Mysql server

In [121]:
pip install mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Collecting mysql-connector-python
  Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/17.7 MB 3.5 MB/s eta 0:00:05
   -- ------------------------------------- 1.0/17.7 MB 3.2 MB/s eta 0:00:06
   ---- ----------------------------------- 2.1/17.7 MB 3.6 MB/s eta 0:00:05
   ------ --------------------------------- 2.9/17.7 MB 3.7 MB/s eta 0:00:04
   -------- ------------------------------- 3.7/17.7 MB 3.9 MB/s eta 0:00:04
   ---------- ----------------------------- 4.7/17.7 MB 3.9 MB/s eta 0:00:04
   ------------ --------------------------- 5.5/17.7 MB 4.0 MB/s eta 0:00:04
   -------------- ------------------------- 6.3/17.7 MB 4.0 MB/s eta 0:00:03
   ---------------- ----------------------- 7.1/17.7 MB 4.0 MB/s eta 0:00:03
   ------------------ --------------------- 8.1/17.7 MB 4.0 MB/s eta 0:00:03
   -------------------- ------------------- 8.9/17.7 MB 4.1 MB/s eta 0:00:03
   --------------------- ------------------ 9.7/17.7 MB 4.1 MB/s eta 0:00:02
   ------------------------ --------------- 10.7/17.7 MB 4.1 MB/s eta 0:00:02
   -------------------------- ------------- 11.5/17.7 MB 4.1 MB/s eta 0:00:02
   ---------------------------- ----------- 12.6/17.7 MB 4.1 MB/s eta 0:00:02
   ------------------------------ --------- 13.4/17.7 MB 4.1 MB/s eta 0:00:02
   -------------------------------- ------- 14.4/17.7 MB 4.1 MB/s eta 0:00:01
   ---------------------------------- ----- 15.2/17.7 MB 4.1 MB/s eta 0:00:01
   ------------------------------------ --- 16.0/17.7 MB 4.1 MB/s eta 0:00:01
   ------------------------------------- -- 16.8/17.7 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 4.0 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0
Note: you may need to restart the kernel to use updated packages.

In [131]:
from sqlalchemy import create_engine

# MySQL connection
user = "root"
password = "11212671"
host = "localhost"
database = "data_analyst_project"

engine = create_engine(
    f"mysql+mysqlconnector://{user}:{password}@{host}/{database}"
)

print("Successfully connected to MySQL!")

# Table name
table_name = "customer_behavior_analysis"

# Load data
data.to_sql(table_name, engine, if_exists='replace', index=False)

print(f"Data Successfully loaded into table '{table_name} in database 'data_analyst_project'")

Successfully connected to MySQL!
Data Successfully loaded into table 'customer_behavior_analysis in database 'data_analyst_project'